export const woodSpecies = [
  { value: 'walnut', label: 'Walnut', type: 'hardwood', color: 'Dark brown', hardness: 1010 },
  { value: 'maple', label: 'Maple', type: 'hardwood', color: 'Light cream', hardness: 1450 },
  { value: 'oak', label: 'Oak', type: 'hardwood', color: 'Light to medium brown', hardness: 1360 },
  { value: 'cherry', label: 'Cherry', type: 'hardwood', color: 'Reddish brown', hardness: 950 },
  { value: 'ash', label: 'Ash', type: 'hardwood', color: 'Light brown', hardness: 1320 },
  { value: 'birch', label: 'Birch', type: 'hardwood', color: 'Pale cream', hardness: 1260 },
  { value: 'poplar', label: 'Poplar', type: 'hardwood', color: 'Pale yellow-green', hardness: 540 },
  { value: 'alder', label: 'Alder', type: 'hardwood', color: 'Light brown', hardness: 590 },
  { value: 'hickory', label: 'Hickory', type: 'hardwood', color: 'Light to medium brown', hardness: 1820 },
  { value: 'elm', label: 'Elm', type: 'hardwood', color: 'Light brown', hardness: 830 },
  { value: 'pine-white', label: 'Pine (White)', type: 'softwood', color: 'Light yellow', hardness: 420 },
  { value: 'pine-yellow', label: 'Pine (Yellow)', type: 'softwood', color: 'Yellow', hardness: 870 },
  { value: 'douglas-fir', label: 'Douglas Fir', type: 'softwood', color: 'Light reddish brown', hardness: 660 },
  { value: 'cedar-western-red', label: 'Cedar (Western Red)', type: 'softwood', color: 'Reddish brown', hardness: 350 },
  { value: 'spruce', label: 'Spruce', type: 'softwood', color: 'Pale cream', hardness: 440 },
  { value: 'hemlock', label: 'Hemlock', type: 'softwood', color: 'Light brown', hardness: 500 },
  { value: 'cypress', label: 'Cypress', type: 'softwood', color: 'Light brown', hardness: 510 },
  { value: 'mahogany', label: 'Mahogany', type: 'exotic', color: 'Reddish brown', hardness: 800 },
  { value: 'teak', label: 'Teak', type: 'exotic', color: 'Golden brown', hardness: 1155 },
  { value: 'padauk', label: 'Padauk', type: 'exotic', color: 'Orange-red', hardness: 1725 },
  { value: 'purpleheart', label: 'Purpleheart', type: 'exotic', color: 'Purple', hardness: 2500 },
  { value: 'rosewood', label: 'Rosewood', type: 'exotic', color: 'Dark brown with reddish highlights', hardness: 1780 },
  { value: 'wenge', label: 'Wenge', type: 'exotic', color: 'Dark brown', hardness: 1990 },
  { value: 'ebony', label: 'Ebony', type: 'exotic', color: 'Black', hardness: 3220 },
  { value: 'bubinga', label: 'Bubinga', type: 'exotic', color: 'Reddish brown', hardness: 1990 },
  { value: 'sycamore', label: 'Sycamore', type: 'hardwood', color: 'Pale cream', hardness: 1450 },
  { value: 'cottonwood', label: 'Cottonwood', type: 'hardwood', color: 'Light brown', hardness: 350 },
  { value: 'boxelder', label: 'Boxelder', type: 'hardwood', color: 'Creamy with red streaks', hardness: 700 },
  { value: 'hackberry', label: 'Hackberry', type: 'hardwood', color: 'Light to medium brown', hardness: 820 },
  { value: 'red-maple', label: 'Red Maple', type: 'hardwood', color: 'Light red-brown', hardness: 950 },
  { value: 'silver-maple', label: 'Silver Maple', type: 'hardwood', color: 'Pale cream', hardness: 700 },
  { value: 'white-oak', label: 'White Oak', type: 'hardwood', color: 'Light to medium brown', hardness: 1360 },
  { value: 'red-oak', label: 'Red Oak', type: 'hardwood', color: 'Reddish brown', hardness: 1290 },
  { value: 'eastern-white-pine', label: 'Eastern White Pine', type: 'softwood', color: 'Pale yellow', hardness: 420 },
  { value: 'sugar-pine', label: 'Sugar Pine', type: 'softwood', color: 'Light cream', hardness: 380 },
  { value: 'redwood', label: 'Redwood', type: 'softwood', color: 'Reddish brown', hardness: 450 },
  { value: 'ipe', label: 'Ipe', type: 'exotic', color: 'Dark brown', hardness: 3680 },
  { value: 'merbau', label: 'Merbau', type: 'exotic', color: 'Medium brown', hardness: 1925 },
  { value: 'sapele', label: 'Sapele', type: 'exotic', color: 'Reddish brown', hardness: 1410 },
  { value: 'koa', label: 'Koa', type: 'exotic', color: 'Golden to reddish brown', hardness: 1820 },
  { value: 'african-mahogany', label: 'African Mahogany', type: 'exotic', color: 'Reddish brown', hardness: 800 },
  { value: 'beech', label: 'Beech', type: 'hardwood', color: 'Light brown', hardness: 1300 },
  { value: 'lacewood', label: 'Lacewood', type: 'exotic', color: 'Light brown with reddish pattern', hardness: 1350 },
  { value: 'olivewood', label: 'Olivewood', type: 'exotic', color: 'Golden brown with darker streaks', hardness: 3450 },
  { value: 'zebrawood', label: 'Zebrawood', type: 'exotic', color: 'Light brown with dark stripes', hardness: 1575 },
  { value: 'chestnut', label: 'Chestnut', type: 'hardwood', color: 'Light brown', hardness: 540 },
  { value: 'redheart', label: 'Redheart', type: 'exotic', color: 'Deep red', hardness: 1850 },
  { value: 'yew', label: 'Yew', type: 'hardwood', color: 'Reddish brown', hardness: 1540 },
  { value: 'santos-mahogany', label: 'Santos Mahogany', type: 'exotic', color: 'Deep reddish brown', hardness: 2200 },
  { value: 'makore', label: 'Makore', type: 'exotic', color: 'Reddish brown', hardness: 1210 },
  { value: 'jacaranda', label: 'Jacaranda', type: 'exotic', color: 'Purple-brown', hardness: 2600 },
  { value: 'ironwood', label: 'Ironwood', type: 'hardwood', color: 'Dark brown', hardness: 3500 },
  { value: 'ginkgo', label: 'Ginkgo', type: 'hardwood', color: 'Pale yellow', hardness: 540 },
  { value: 'fir-noble', label: 'Fir (Noble)', type: 'softwood', color: 'Light brown', hardness: 660 },
  { value: 'larch', label: 'Larch', type: 'softwood', color: 'Red-brown', hardness: 830 },
  { value: 'white-ash', label: 'White Ash', type: 'hardwood', color: 'Light brown', hardness: 1320 },
  { value: 'red-elm', label: 'Red Elm', type: 'hardwood', color: 'Reddish brown', hardness: 960 },
  { value: 'american-elm', label: 'American Elm', type: 'hardwood', color: 'Light brown', hardness: 830 },
  { value: 'black-cherry', label: 'Black Cherry', type: 'hardwood', color: 'Reddish brown', hardness: 950 },
  { value: 'western-red-cedar', label: 'Western Red Cedar', type: 'softwood', color: 'Reddish brown', hardness: 350 },
  { value: 'eastern-hemlock', label: 'Eastern Hemlock', type: 'softwood', color: 'Light brown', hardness: 500 },
  { value: 'spruce-sitka', label: 'Spruce (Sitka)', type: 'softwood', color: 'Pale cream', hardness: 440 },
  { value: 'douglas-fir-coast', label: 'Douglas Fir (Coast)', type: 'softwood', color: 'Reddish brown', hardness: 660 },
  { value: 'afromosia', label: 'Afromosia', type: 'exotic', color: 'Golden brown', hardness: 1950 },
  { value: 'red-cedar-eastern', label: 'Red Cedar (Eastern)', type: 'softwood', color: 'Reddish brown', hardness: 350 },
  { value: 'basswood', label: 'Basswood', type: 'softwood', color: 'Pale cream', hardness: 410 },
  { value: 'butternut', label: 'Butternut', type: 'hardwood', color: 'Light brown', hardness: 490 },
  { value: 'yellowheart', label: 'Yellowheart', type: 'exotic', color: 'Bright yellow', hardness: 1600 },
  { value: 'canarywood', label: 'Canarywood', type: 'exotic', color: 'Yellow with dark streaks', hardness: 1550 },
  { value: 'cumaru', label: 'Cumaru', type: 'exotic', color: 'Reddish brown', hardness: 3540 },
  { value: 'tigerwood', label: 'Tigerwood', type: 'exotic', color: 'Reddish brown with dark stripes', hardness: 2350 },
  { value: 'wamara', label: 'Wamara', type: 'exotic', color: 'Golden brown', hardness: 1620 },
  { value: 'purpleheart-violet', label: 'Purpleheart (Violet)', type: 'exotic', color: 'Purple', hardness: 2520 },
  { value: 'massaranduba', label: 'Massaranduba', type: 'exotic', color: 'Red-brown', hardness: 2800 },
  { value: 'iroko', label: 'Iroko', type: 'exotic', color: 'Golden brown', hardness: 1720 },
  { value: 'balsa', label: 'Balsa', type: 'softwood', color: 'Light cream', hardness: 100 },
];
